In [3]:
import numpy as np
import time

python_list = list(range(10_000_000))

start = time.time()
res = [x * 2 for x in python_list]
print(f"Python List: {time.time() - start:.4f}s")

numpy_array = np.array(10_000_000)
start = time.time()
res_np = numpy_array * 2
print(f"NumPy Array: {time.time() - start:.4f}s")


Python List: 0.7345s
NumPy Array: 0.0001s


In [75]:
#Mảng một chiều
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
print(type(arr1d))

print("\n")

# Mảng 2 chiều
arr2d = np.array([[1, 2, 3],[4, 5, 6]])
print(arr2d)
print(type(arr2d))

print("\n")

#Mảng 3 chiều (dạng khối)
arr3d = np.array([[[1, 2,], [3,4]], [[5, 6],[7,8]]])
print(arr3d.shape)

arr4d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr4d_reshape = arr4d.reshape(3,4)
print(arr4d_reshape)
flatten = arr4d_reshape.flatten()
print(flatten)
print(arr4d_reshape.T)

[1 2 3 4 5]
<class 'numpy.ndarray'>


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


(2, 2, 2)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [14]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [17]:
np.empty((2,2))

array([[0.00000000e+000, 8.54239581e-312],
       [8.54264909e-312, 8.54239581e-312]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.diag((1, 2, 3, 4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

In [47]:
np.random.seed(42)
np.random.rand(3, 4)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [51]:
np.random.randn(3, 4)

array([[-1.47852199, -0.71984421, -0.46063877,  1.05712223],
       [ 0.34361829, -1.76304016,  0.32408397, -0.38508228],
       [-0.676922  ,  0.61167629,  1.03099952,  0.93128012]])

In [54]:
np.random.randint(0, 10, size=(3, 4))

array([[4, 9, 6, 6],
       [8, 9, 9, 2],
       [6, 0, 3, 3]], dtype=int32)

In [58]:
np.random.choice( [1, 2, 3, 4, 5] , size=100)

array([2, 2, 3, 2, 1, 5, 4, 2, 1, 4, 5, 4, 1, 4, 3, 4, 2, 2, 3, 1, 2, 5,
       2, 2, 1, 4, 2, 3, 4, 5, 1, 5, 4, 4, 4, 5, 4, 5, 4, 3, 4, 5, 2, 4,
       2, 3, 1, 3, 4, 2, 2, 5, 2, 5, 1, 4, 5, 1, 2, 2, 1, 2, 1, 5, 5, 1,
       5, 5, 5, 3, 4, 2, 3, 5, 1, 5, 4, 5, 1, 4, 5, 4, 2, 2, 5, 4, 1, 5,
       2, 2, 5, 4, 2, 4, 2, 2, 3, 2, 1, 5])

In [60]:
np.random.normal(loc= 0, scale= 1, size=100)

array([ 4.56078399e-02,  3.89179576e-01, -2.67400638e-01, -1.03841117e-01,
        8.43574023e-01, -1.06632148e+00, -7.01813443e-01, -9.67111055e-01,
        1.43675467e+00, -7.01699977e-01, -1.43283259e-01, -6.00604681e-01,
       -3.08177953e-01, -7.37429466e-01,  4.62724314e-01, -1.04085015e+00,
       -1.35245055e+00, -5.58420369e-01, -7.98235218e-01, -1.33784482e+00,
       -3.23372799e-01, -1.66011742e+00,  1.72774763e+00, -1.49260136e+00,
       -6.46299499e-01, -4.03554957e-01,  1.68468496e+00, -1.73031531e+00,
        1.42050092e-01,  1.03715846e+00, -3.09743103e-01, -1.16981703e+00,
       -1.07984964e-01,  1.52710126e+00, -6.15785845e-01,  1.43618347e+00,
        2.58666912e-01,  1.23251421e+00,  2.18683092e-01, -4.84375692e-01,
        1.63885999e+00,  2.25235353e-01,  1.66429536e-01,  8.07555632e-01,
        9.24152383e-01,  8.12856464e-01, -1.35072195e+00, -6.37235532e-01,
       -6.56528951e-01, -7.79080229e-01, -8.72103765e-01, -6.71023911e-01,
        3.35948743e-01,  

In [61]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(arr2[1,2])

arr2[2, :]

arr2[arr2 > 5]  =0
print(arr2)

7
[[1 2 3 4]
 [5 0 0 0]
 [0 0 0 0]]


In [77]:
a = np.array([[1,2], [3,4]])
b=np.array([[5,6],[7,8]])
vab = np.stack((a,b))
print(vab)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [78]:
hab = np.hstack((a,b))
print(hab)

[[1 2 5 6]
 [3 4 7 8]]


In [79]:
ab1 = np.concatenate((a,b), axis=1)
ab2 = np.concatenate((a,b), axis=0)
print(ab1)
print(ab2)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [80]:
arr5 = np.arange(12).reshape(4,3)
print(arr5)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [81]:
varr= np.vsplit(arr5,2)
print(varr)

[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]])]


In [82]:
harr = np.hsplit(arr5,3)
print(harr)

[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]


In [89]:
row = np.array([1,2,3])
arr2dd= np.array([[1,2,3],[4,5,6]])
arr2dd + row

array([[2, 4, 6],
       [5, 7, 9]])

In [83]:
np.array([1,2,3,4])+10

array([11, 12, 13, 14])

In [ ]:
# Giải hệ PT tuyến tình
# 2x + 3y = 8
# 3x + 4y = 11

A=np.array([[2,3],[3,4]])
b =np.array([8,11])
x= np.linalg.solve(A,b)
print(x)
print(a@x)

[1. 2.]
[ 8. 11.]


In [117]:
#Giải hệ
# x + 2y + 3z= 14
# 2x+5y+z = 18
# 4x+6y+8z=32

#1
A = np.array([[1,2,3],[2,5,1],[4,6,8]], dtype=float)
b= np.array([14,18,32],dtype=float)
x= np.linalg.solve(A,b)
print(x)
print(A @ x)
#2
M = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(M)

for i in range(len(eigenvalues)):
    lam = eigenvalues[i].real
    v = eigenvectors[:, i].real
    print(M @ v, "~", lam * v)

[-6.85714286  5.71428571  3.14285714]
[14. 18. 32.]
[2.68328157 1.34164079] ~ [2.68328157 1.34164079]
[1.41421356 1.41421356] ~ [1.41421356 1.41421356]
